-- Cross-DB employee table scripts have been split per vendor to avoid parser errors
-- and accidental execution of the wrong dialect in a single file.
--
-- Use the appropriate script for your target database:
--   - PostgreSQL: scripts/sql/postgresql/create_employee_table.sql
--   - SQL Server: scripts/sql/sqlserver/create_employee_table.sql
--   - Oracle:     scripts/sql/oracle/create_employee_table.sql
--
-- This file intentionally contains no executable SQL to prevent dialect conflicts.