version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: csvapp
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: csvapp_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U csvapp"]
      interval: 10s
      timeout: 5s
      retries: 5

  # SQL Server
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "${SQLSERVER_SA_PASSWORD}"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "${SQLSERVER_SA_PASSWORD}" -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 5s
      retries: 5

  # Oracle XE (Express Edition)
  oracle:
    image: container-registry.oracle.com/database/express:latest
    environment:
      ORACLE_PWD: ${ORACLE_PWD}
    ports:
      - "1521:1521"
    volumes:
      - oracle_data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "system/${ORACLE_PWD}@//localhost:1521/XE", "AS", "SYSDBA"]
      interval: 30s
      timeout: 10s
      retries: 3

  # SFTP Server
  sftp:
    image: atmoz/sftp
    ports:
      - "2222:22"
    command: csvapp:${SFTP_PASSWORD}:::upload
    volumes:
      - sftp_data:/home/csvapp/upload
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "22"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres_data:
  sqlserver_data:
  oracle_data:
  sftp_data: