name: CI - .NET with SonarCloud Analysis

on:
  push:
    branches: [ main, develop, feature/* ]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main, develop ]

jobs:
  sonarcloud:
    name: Build, Test & SonarCloud Analysis
    runs-on: windows-latest

    steps:
      # ===== SETUP =====
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu' # Required for SonarCloud

      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # Disable shallow clones for better analysis relevancy

      - name: Setup .NET 9.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      # ===== CACHE =====
      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache SonarCloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v4
        with:
          path: .\.sonar\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      # ===== INSTALL TOOLS =====
      - name: Install SonarCloud scanner for .NET
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          New-Item -Path .\.sonar\scanner -ItemType Directory -Force
          dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner

      - name: Install dotnet-coverage
        shell: powershell
        run: |
          dotnet tool install --global dotnet-coverage

      # ===== BUILD PREPARATION =====
      - name: Create basic structure if missing
        shell: powershell
        run: |
          if (!(Test-Path "CSVTransferApp.sln")) {
              Write-Output "Creating basic solution structure..."
              dotnet new sln -n CSVTransferApp
              
              # Create minimal console app for CI
              New-Item -ItemType Directory -Path "src\CSVTransferApp.Console" -Force
              dotnet new console -n CSVTransferApp.Console -o src\CSVTransferApp.Console --framework net9.0
              dotnet sln add src\CSVTransferApp.Console\CSVTransferApp.Console.csproj
              
              Write-Output "✅ Basic structure created for CI"
          } else {
              Write-Output "✅ Solution file exists"
          }

      # ===== SONAR ANALYSIS + BUILD + TEST =====
      - name: Begin SonarCloud analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: |
          .\.sonar\scanner\dotnet-sonarscanner begin `
            /k:"${{ github.repository_owner }}_${{ github.event.repository.name }}" `
            /o:"${{ github.repository_owner }}" `
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}" `
            /d:sonar.host.url="https://sonarcloud.io" `
            /d:sonar.exclusions="**/bin/**,**/obj/**,**/logs/**,**/temp/**,**/*.Designer.cs" `
            /d:sonar.coverage.exclusions="**/Tests/**,**/TestData/**,**/Mocks/**" `
            /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml"

      - name: Restore dependencies
        run: dotnet restore --verbosity normal

      - name: Build solution
        run: dotnet build --configuration Release --no-restore --verbosity minimal

      - name: Run tests with coverage
        shell: powershell
        run: |
          # Cerca progetti di test
          $testProjects = Get-ChildItem -Path . -Recurse -Include "*Tests.csproj"
          
          if ($testProjects.Count -gt 0) {
              Write-Output "Found $($testProjects.Count) test project(s)"
              
              # Esegui test con coverage
              dotnet-coverage collect "dotnet test --configuration Release --no-build --verbosity normal --logger trx --results-directory TestResults" -f xml -o "coverage.opencover.xml"
              
              Write-Output "✅ Tests completed with coverage"
          } else {
              Write-Output "⚠️ No test projects found, creating dummy coverage file"
              
              # Crea file coverage vuoto per SonarCloud
              $coverageXml = @"
          <?xml version="1.0" encoding="utf-8"?>
          <CoverageSession>
            <Summary numSequencePoints="0" visitedSequencePoints="0" numBranchPoints="0" visitedBranchPoints="0" sequenceCoverage="0" branchCoverage="0" maxCyclomaticComplexity="0" minCyclomaticComplexity="0" />
            <Modules>
            </Modules>
          </CoverageSession>
          "@
              Set-Content -Path "coverage.opencover.xml" -Value $coverageXml
          }

      - name: End SonarCloud analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: |
          .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"

      # ===== UPLOAD ARTIFACTS =====
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-${{ runner.os }}
          path: |
            TestResults/*.trx
            coverage.opencover.xml
          retention-days: 30

      # ===== BUILD SUMMARY =====
      - name: Generate build summary
        if: always()
        shell: powershell
        run: |
          Write-Output "## 🔍 SonarCloud Analysis Results" >> $env:GITHUB_STEP_SUMMARY
          Write-Output "" >> $env:GITHUB_STEP_SUMMARY
          Write-Output "### 📊 Analysis Information:" >> $env:GITHUB_STEP_SUMMARY
          Write-Output "- **Project**: ${{ github.repository }}" >> $env:GITHUB_STEP_SUMMARY
          Write-Output "- **Branch**: ${{ github.ref_name }}" >> $env:GITHUB_STEP_SUMMARY
          Write-Output "- **Commit**: ${{ github.sha }}" >> $env:GITHUB_STEP_SUMMARY
          Write-Output "" >> $env:GITHUB_STEP_SUMMARY
          Write-Output "🔗 **[View Results on SonarCloud](https://sonarcloud.io/project/overview?id=${{ github.repository_owner }}_${{ github.event.repository.name }})**" >> $env:GITHUB_STEP_SUMMARY

  # ===== JOB PARALLELO PER LINUX (opzionale) =====
  build-linux:
    name: Build Test (Linux)
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup .NET 9.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore --verbosity normal

      - name: Build solution
        run: dotnet build --configuration Release --no-restore --verbosity minimal

      - name: Run tests
        run: dotnet test --configuration Release --no-build --verbosity normal
