name: PROD - Build & Release .NET CSV Transfer App

on:
  pull_request:
    types:
      - closed
    branches:
      - main
  push:
    tags:
      - 'v*'

# Security: Explicit permissions for CodeQL compliance
permissions:
  contents: write
  pull-requests: read
  actions: write

jobs:
  build-release:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
      actions: write
      
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            runtime: linux-x64
            artifact: linux-x64
          - os: windows-latest
            runtime: win-x64
            artifact: win-x64

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Create and push production tag from latest dev version
        if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
        shell: pwsh
        run: |
          git fetch --tags
          $all_tags = git tag --list
          $dev_tags = @()
          foreach ($tag in $all_tags) {
            if ($tag -match '^v(\d+)\.(\d+)\.(\d+)-dev') {
              $dev_tags += $tag
            }
          }
          if ($dev_tags.Count -eq 0) {
            $new_version = "1.0.0"
          } else {
            # Find the highest version from dev tags
            $version_numbers = @()
            foreach ($tag in $dev_tags) {
              if ($tag -match '^v(\d+)\.(\d+)\.(\d+)-dev') {
                $major = [int]$matches[1]
                $minor = [int]$matches[2]
                $patch = [int]$matches[3]
                $version_numbers += [PSCustomObject]@{
                  Major = $major
                  Minor = $minor  
                  Patch = $patch
                  FullVersion = "$major.$minor.$patch"
                }
              }
            }
<<<<<<< HEAD
            # Sort and get the highest version
            $highest = $version_numbers | Sort-Object Major,Minor,Patch -Descending | Select-Object -First 1
            if ($highest) {
              $new_version = $highest.FullVersion
            } else {
              $new_version = "1.0.0"
            }
=======
            $new_version = "$($highest_version.major).$($highest_version.minor).$($highest_version.patch)"
>>>>>>> cdbe124d72989803efba4a92117aa758d6d5038a
          }
          $tag = "v$new_version"
          if ($all_tags -contains $tag) {
            Write-Output "Tag $tag already exists, skipping."
            exit 0
          }
          git config user.email "csvtransferapp.bot@gmail.com"
          git config user.name "CSV Transfer App Bot"
          git tag $tag
          git push origin $tag

      - name: Setup .NET 9.0
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '9.0.x'

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}

      - name: Restore dependencies
        run: dotnet restore CSVTransferApp.sln

      - name: Build solution
        run: dotnet build CSVTransferApp.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test CSVTransferApp.sln --configuration Release --no-build --verbosity normal

      - name: Publish application
        shell: pwsh
        run: |
          dotnet publish src/CSVTransferApp.Console/CSVTransferApp.Console.csproj `
            --configuration Release `
            --runtime ${{ matrix.runtime }} `
            --self-contained true `
            --output ./publish/${{ matrix.artifact }} `
            /p:PublishSingleFile=true `
            /p:IncludeNativeLibrariesForSelfExtract=true

      - name: Publish framework-dependent (DLL)
        shell: pwsh
        run: |
          dotnet publish src/CSVTransferApp.Console/CSVTransferApp.Console.csproj `
            --configuration Release `
            --output ./publish/${{ matrix.artifact }}-fx

      - name: Copy publish to deploy folder and create archives (Windows)
        if: ${{ matrix.runtime == 'win-x64' }}
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Path "./deploy/windows/publish" -Force
          New-Item -ItemType Directory -Path "./deploy/windows/publish-fx" -Force
          New-Item -ItemType Directory -Path "./deploy/windows/archives" -Force
          Copy-Item -Path "./publish/win-x64/*" -Destination "./deploy/windows/publish/" -Recurse -Force
          Copy-Item -Path "./publish/win-x64-fx/*" -Destination "./deploy/windows/publish-fx/" -Recurse -Force -ErrorAction SilentlyContinue
          Compress-Archive -Path "./deploy/windows/publish/*" -DestinationPath "./deploy/windows/archives/CSVTransferApp-win-selfcontained.zip" -Force
          Compress-Archive -Path "./deploy/windows/publish-fx/*" -DestinationPath "./deploy/windows/archives/CSVTransferApp-win-fx.zip" -Force

      - name: Copy publish to deploy folder and create archives (Linux)
        if: ${{ matrix.runtime == 'linux-x64' }}
        run: |
          mkdir -p ./deploy/linux/publish ./deploy/linux/publish-fx ./deploy/linux/archives
          cp -r ./publish/linux-x64/* ./deploy/linux/publish/ || true
          cp -r ./publish/linux-x64-fx/* ./deploy/linux/publish-fx/ || true
          tar -czf ./deploy/linux/archives/CSVTransferApp-linux-selfcontained.tar.gz -C ./deploy/linux/publish .
          tar -czf ./deploy/linux/archives/CSVTransferApp-linux-fx.tar.gz -C ./deploy/linux/publish-fx .

      - name: Create release package (Windows)
        if: ${{ matrix.runtime == 'win-x64' }}
        shell: pwsh
        run: |
          Push-Location -Path "publish/${{ matrix.artifact }}"
          $out = "../../CSVTransferApp-${{ github.ref_name }}-${{ matrix.artifact }}.zip"
          Compress-Archive -Path * -DestinationPath $out -Force
          Pop-Location

      - name: Create release package (Linux)
        if: ${{ matrix.runtime == 'linux-x64' }}
        run: |
          mkdir -p ./publish/${{ matrix.artifact }}
          tar -czf CSVTransferApp-${{ github.ref_name }}-${{ matrix.artifact }}.tar.gz -C publish/${{ matrix.artifact }} .

      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: csvtransferapp-${{ matrix.artifact }}
          path: |
            CSVTransferApp-${{ github.ref_name }}-${{ matrix.artifact }}.*
            deploy/windows/archives/**
            deploy/linux/archives/**

  create-release:
    needs: build-release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
      
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Download Windows artifacts
        uses: actions/download-artifact@v5
        with:
          name: csvtransferapp-win-x64
          path: ./artifacts/win

      - name: Download Linux artifacts
        uses: actions/download-artifact@v5
        with:
          name: csvtransferapp-linux-x64
          path: ./artifacts/linux

      - name: Create and push release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: "CSVTransferApp Release ${{ github.ref_name }}"
          body: "Automated release for ${{ github.ref_name }}"
          files: |
            ./artifacts/win/deploy/windows/archives/CSVTransferApp-win-selfcontained.zip
            ./artifacts/win/deploy/windows/archives/CSVTransferApp-win-fx.zip
            ./artifacts/linux/deploy/linux/archives/CSVTransferApp-linux-selfcontained.tar.gz
            ./artifacts/linux/deploy/linux/archives/CSVTransferApp-linux-fx.tar.gz
